services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  todoapi:
    build:
      context: .
      dockerfile: TodoApi/Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=tododb;Username=postgres;Password=postgres

volumes:
  postgres_data: